# Generated by Django 4.0.4 on 2023-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bug_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
