# Generated by Django 4.0.4 on 2023-04-29 04:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bug_severity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('minor', 'MINOR'), ('normal', 'NORMAL'), ('major', 'MAJOR'), ('critical', 'CRITICAL'), ('blocker', 'BLOCKER')], max_length=20, null=True),
        ),
    ]
