# Generated by Django 4.0.4 on 2023-05-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230429_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/bug_files')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.bug')),
            ],
        ),
    ]
