# Generated by Django 4.0.4 on 2023-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bugmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='BugMedia',
        ),
    ]
