# Generated by Django 4.0.4 on 2023-05-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bug_files_delete_bugmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='files',
        ),
        migrations.CreateModel(
            name='BugMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bug')),
            ],
        ),
    ]
