# Generated by Django 4.0.4 on 2023-05-04 08:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_bug_files_bugmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugmedia',
            name='file',
            field=models.FileField(upload_to='media', validators=[core.models.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'log'])]),
        ),
    ]
